---
title: "07-week7"
author: "Kathleen Durkin"
date: "2025-05-13"
format: html
editor: visual
---

# Week 07 Questions

## What is your current grade in the class? How many issues are open in our research repository?

I currently have all 5/5 scores, with the exception of a 3/5 score on my Week 5 Assignment, which I failed to complete (I think I forgot to do the IGV visualization)

## Re-reading this week’s reading, what are 2 things that resonate with you now that made little practical sense in week 2. What is one aspect that you still wonder about or is unclear?

I already have a bioinformatics background, so the reading made good sesne to me in Week 2. One thing I've gained new appreciation of in the last few weeks, as I've been planning a sequencing experiment myself for the first time, is the importance of choosing the right library prep and sequencing options for our samples and desired output.

## What is epigenetics and how could it relate to your own research project?

Epigenetics is the study of molecular features that impact expression without altering the nucleotide sequence (e.g., various chemical modifications of DNA and RNA molecules, non-coding RNAs). My entire degree is studying epigenetic mechanisms (miRNA, lncRNA, siRNA, DNA methylation) and their interactions with gene expressison.

## Describe what a GFF file is?

GFF = Genome Feature Format. These files are used broadly to store information on features of interest (e.g. genomic regions, SNPs, etc.). GFF format has specified columns to contain the information types used to define genomic coordinates (chromosome/scaffold, start position, end position, strand, etc.), and has an additional column to define metadata/descriptive information/etc.

## What are two ways describing CG motifs could have value?

1. Studying DNA methylation, which primarily occurs in a CpG context (in animals)

2. Characterizing the presence, distribution, and methylation status of CpG island, which occur in specific relation to gene bodies.


